// import 'package:flutter_test/flutter_test.dart';
// import 'package:kebormed/features/login/bloc/bloc.dart';
// import 'package:mockito/mockito.dart';
// import 'package:kebormed/core/utils/app_storage.dart';
// import 'package:mockito/annotations.dart';

// import 'login_bloc_test.mocks.dart';
// // Generated by mockito

// @GenerateMocks([AppStorage])
// void main() {
//   late LoginBloc loginBloc;
//   late MockAppStorage mockAppStorage;

//   setUp(() {
//     mockAppStorage = MockAppStorage();
//     loginBloc = LoginBloc();
//   });

//   tearDown(() {
//     loginBloc.close();
//   });

//   test('Initial state should be EmptyState', () {
//     expect(loginBloc.state, const EmptyState());
//   });

//   test('Load saved user credentials from AppStorage', () async {
//     // when(mockAppStorage.getUsername()).thenReturn('testUser');
//     // when(mockAppStorage.getPassword()).thenReturn('testPassword');
//     // when(mockAppStorage.getRememberMe()).thenReturn(true);

//     // loginBloc.loadUserCredentials();

//     expect(loginBloc.userNameController.text, 'testUser');
//     // expect(loginBloc.passwordController.text, 'testPassword');
//     expect(loginBloc.isRemembered, true);
//   });

//   test('Save user credentials when "Remember Me" is selected', () async {
//     loginBloc.isRemembered = true;
//     loginBloc.userNameController.text = 'testUser';
//     loginBloc.passwordController.text = 'testPassword';

//     // loginBloc.saveUserCredentials(MockBuildContext());

//     //   verify(
//     //       mockAppStorage.saveCredentials('testUser', 'testPassword', true, any));
//   });

//   test('Clear user credentials when "Remember Me" is not selected', () async {
//     loginBloc.isRemembered = false;

//     // loginBloc.saveUserCredentials(MockBuildContext());

//     // verify(mockAppStorage.clearCredentials());
//   });

//   test('Token generation works correctly', () {
//     loginBloc.userNameController.text = 'testUser';
//     loginBloc.passwordController.text = 'testPassword';

//     loginBloc.generateToken();

//     expect(loginBloc.token.isNotEmpty, true);
//   });
// }
